# Generated by Django 4.2.6 on 2023-10-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="teams.team"
            ),
        ),
    ]
